### ISSUE TITLE
Pipeline.py is nonstandard needs to be lower case

### ISSUE THREAD

**Issue by jayventi** [codeforboston/Scrapple#8]
There is at least one Python library that starts with nonstandard capitalization which will cause a problem for non-NTSF systems. Pipeline.py is nonstandard and will cause problems when gets called in data_manager.py, in lowercase form l4 from. import pipeline, the filename should be in standard lowercase.

**Comment by bdougsand** [comment]
This was resolved in commit 87b9abd4384e58a8b57d1b2bac2325a427432268.
